# Generated by Django 4.0.4 on 2022-05-23 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaza',
            fields=[
                ('IdChaza', models.AutoField(primary_key=True, serialize=False)),
                ('NombreChaza', models.CharField(max_length=40)),
                ('Puntuacion', models.FloatField()),
                ('Descripcion', models.TextField()),
                ('Ubicacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='comensales',
            fields=[
                ('IdComensal', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Contrasena', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('IdTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTipoUsuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DuenoChaza',
            fields=[
                ('IdDuenoChaza', models.AutoField(primary_key=True, serialize=False)),
                ('IdChaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chaza')),
                ('IdComensal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.comensales')),
            ],
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('IdComentario', models.AutoField(primary_key=True, serialize=False)),
                ('DescripcionComentario', models.TextField(max_length=400)),
                ('IdChaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chaza')),
                ('IdComensal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.comensales')),
            ],
        ),
        migrations.AddField(
            model_name='comensales',
            name='IdTipoUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tipousuario'),
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('IdCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCategoria', models.CharField(max_length=20)),
                ('IdChaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chaza')),
            ],
        ),
    ]
