# Generated by Django 4.0.4 on 2022-05-23 05:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='comensales',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('IdComensal', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=20)),
                ('RegistroFinalizado', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='chaza',
            fields=[
                ('IdChaza', models.AutoField(primary_key=True, serialize=False)),
                ('NombreChaza', models.CharField(max_length=40)),
                ('Puntuacion', models.FloatField()),
                ('Descripcion', models.TextField()),
                ('Ubicacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('IdTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTipoUsuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DuenoChaza',
            fields=[
                ('IdDuenoChaza', models.AutoField(primary_key=True, serialize=False)),
                ('IdChaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chaza')),
                ('IdComensal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('IdComentario', models.AutoField(primary_key=True, serialize=False)),
                ('DescripcionComentario', models.TextField(max_length=400)),
                ('IdChaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chaza')),
                ('IdComensal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('IdCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCategoria', models.CharField(max_length=20)),
                ('IdChaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chaza')),
            ],
        ),
        migrations.AddField(
            model_name='comensales',
            name='IdTipoUsuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.tipousuario'),
        ),
        migrations.AddField(
            model_name='comensales',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='comensales',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
