# Generated by Django 4.0.4 on 2022-06-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='PuntuacionDada',
            field=models.FloatField(default=0),
        ),
    ]
