# Generated by Django 4.0.4 on 2022-06-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaza',
            name='Descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='chaza',
            name='NombreChaza',
            field=models.CharField(max_length=40, verbose_name='Nombre Chaza'),
        ),
        migrations.AlterField(
            model_name='chaza',
            name='Ubicacion',
            field=models.CharField(max_length=200, verbose_name='Ubicación'),
        ),
    ]
