# Generated by Django 4.0.4 on 2022-05-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comensales',
            name='RegistroFinalizado',
            field=models.IntegerField(default=0),
        ),
    ]
