# Generated by Django 4.0.4 on 2022-06-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaza',
            name='slug',
            field=models.SlugField(default='default', max_length=255, unique=True),
        ),
    ]
