# Generated by Django 4.0.4 on 2022-05-23 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duenochaza',
            name='IdChaza',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.chaza'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
