# Generated by Django 4.0.4 on 2022-06-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_comentarios_puntuaciondada'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaza',
            name='CoordenadaX',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chaza',
            name='CoordenadaY',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
