# Generated by Django 4.0.4 on 2022-06-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_chaza_coordenadax_chaza_coordenaday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaza',
            name='CoordenadaX',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='chaza',
            name='CoordenadaY',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
