# Generated by Django 4.0.4 on 2022-05-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabla_test',
        ),
    ]
